import { CurriculumNode } from "@/types/curriculum-path";

export const grade2EnglishPath: CurriculumNode[] = [
  { id: "g2-describing-learn", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Describing Words", description: "Learn how words can tell us more about people, animals and things.", kind: "lesson", route: "/learn/adjectives", activityId: "english-g2-describing-words", curriculumId: "g2-describing-words", xp: 20, required: true },
  { id: "g2-describing-guided", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Guided Practice", description: "Work through several supported examples before working alone.", kind: "guided_practice", route: "/challenge/g2-guided-1", activityId: "g2-describing-guided", curriculumId: "g2-describing-words", xp: 30, required: true },
  { id: "g2-describing-independent", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Independent Practice", description: "Show what you know without the guided steps.", kind: "independent_practice", route: "/challenge/g2-independent-1", activityId: "g2-describing-independent", curriculumId: "g2-describing-words", xp: 40, required: true },
  { id: "g2-reading-describing", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Reading Adventure", description: "Find and understand describing words inside a Grade 2 story.", kind: "story", route: "/story/benchmark-grade-2-the-garden-clock", activityId: "benchmark-grade-2-the-garden-clock", curriculumId: "g2-describing-words", xp: 50, required: true },
  { id: "g2-composition-describing", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Sentence Builder", description: "Use describing words to build clear sentences.", kind: "independent_practice", route: "/challenge/g2-sentence-1", activityId: "g2-sentence-builder", curriculumId: "g2-describing-words", xp: 40, required: true },
  { id: "g2-describing-mastery", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Mastery Mission", description: "Bring the skill together in a final challenge.", kind: "mastery", route: "/challenge/g2-mastery-1", activityId: "g2-describing-mastery", curriculumId: "g2-describing-words", xp: 60, required: true },
];
