import { CurriculumNode } from "@/types/curriculum-path";

export const grade2EnglishPath: CurriculumNode[] = [
  { id: "g2-describing-learn", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Describing Words", description: "Learn how words can tell us more about people, animals and things.", kind: "lesson", route: "/learn/adjectives", activityId: "english-g2-describing-words", curriculumId: "g2-describing-words", xp: 20, required: true },
  { id: "g2-describing-guided", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Guided Practice", description: "Try several supported examples before working alone.", kind: "guided_practice", route: "/challenge/g2-describing-guided", activityId: "g2-describing-guided", curriculumId: "g2-describing-words", xp: 30, required: true },
  { id: "g2-describing-independent", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Independent Practice", description: "Show what you know without the guided hints.", kind: "independent_practice", route: "/challenge/g2-describing-independent", activityId: "g2-describing-independent", curriculumId: "g2-describing-words", xp: 40, required: true },
  { id: "g2-reading-describing", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Reading Adventure", description: "Find and use describing words in a Grade 2 story.", kind: "story", route: "/story/g2-garden-clock", activityId: "g2-garden-clock", curriculumId: "g2-describing-words", xp: 50, required: true },
  { id: "g2-composition-describing", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Sentence Builder", description: "Use describing words to build your own sentences.", kind: "independent_practice", route: "/challenge/g2-sentence-builder", activityId: "g2-sentence-builder", curriculumId: "g2-describing-words", xp: 40, required: true },
  { id: "g2-describing-mastery", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", title: "Mastery Mission", description: "Bring the skill together in a final challenge.", kind: "mastery", route: "/challenge/g2-describing-mastery", activityId: "g2-describing-mastery", curriculumId: "g2-describing-words", xp: 60, required: true },
  { id: "g2-actions", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "present and past actions", title: "Actions: Now and Before", description: "Learn how we talk about actions happening now and actions that already happened.", kind: "lesson", route: "/learn/actions", activityId: "english-g2-actions", curriculumId: "g2-actions", xp: 20, required: true },
  { id: "g2-sequencing", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "sentence sequencing", title: "Put the Story in Order", description: "Use simple sequencing words to show what happened first, next and last.", kind: "guided_practice", route: "/challenge/g2-sequencing", activityId: "g2-sequencing", curriculumId: "g2-sequencing", xp: 40, required: true },
  { id: "g2-reading-meaning", grade: 2, subject: "english", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "reading for meaning", title: "Reading Adventure", description: "Read a longer Grade 2 story and show what you understand.", kind: "story", route: "/story/g2-garden-clock", activityId: "g2-garden-clock-comprehension", curriculumId: "g2-reading-meaning", xp: 50, required: true },
];
