"use client";

import { useState } from "react";
import { grade2DescribingIndependent } from "@/content/challenges/grade-2-english";
import { buildPracticeSession, evaluatePracticeSession } from "@/lib/learning-session";
import { getCurrentPlayer, awardXP, recordActivityResult } from "@/lib/player";

export default function Grade2IndependentPage() {
  const [session] = useState(() => buildPracticeSession(grade2DescribingIndependent, 5));
  const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [done, setDone] = useState(false); const [startedAt] = useState(() => Date.now());
  const current = session[index];
  function answer(id: string) { if (selected) return; setSelected(id); if (id === current.correctOptionId) setScore(s => s + 1); }
  function next() { if (!selected) return; const final = index === session.length - 1 ? score + (selected === current.correctOptionId ? 1 : 0) : score; if (index === session.length - 1) { const result = evaluatePracticeSession(final, session.length); const player = getCurrentPlayer(); if (player) { const xp = result.passed ? 40 : 10; awardXP(player.id, xp); recordActivityResult({ id: `g2-independent-${Date.now()}`, playerId: player.id, activityType: "practice_challenge", activityId: "g2-describing-independent", skills: ["grammar", "vocabulary", "reading"], curriculumId: "g2-describing-words", strand: "Reading", subStrand: "Language Patterns and Comprehension", concept: "describing words", correct: result.passed, attempts: session.length, hintsUsed: 0, responseTimeMs: Date.now() - startedAt, xpAwarded: xp, difficulty: 2, timestamp: new Date().toISOString() }); } setScore(final); setDone(true); } else { setIndex(i => i + 1); setSelected(null); } }
  if (done) { const result = evaluatePracticeSession(score, session.length); return <main className="mx-auto max-w-2xl p-6"><div className="rounded-3xl border bg-white p-8 text-center shadow-sm"><div className="text-5xl">{result.passed ? "🚀" : "💪"}</div><h1 className="mt-4 text-3xl font-bold">{result.passed ? "You’re ready!" : "Keep practising!"}</h1><p className="mt-2 text-lg">{score}/{session.length} correct</p><a href="/" className="mt-6 inline-block rounded-2xl bg-slate-900 px-6 py-3 font-semibold text-white">Back to My Journey</a></div></main>; }
  return <main className="mx-auto max-w-2xl p-6"><p className="text-sm font-semibold text-slate-500">GRADE 2 • INDEPENDENT PRACTICE</p><h1 className="mt-2 text-3xl font-bold">Show What You Know</h1><p className="mt-2 text-slate-600">Question {index + 1} of {session.length}</p><div className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">{current.prompt}</h2><div className="mt-6 grid gap-3">{current.options.map(o => <button key={o.id} onClick={() => answer(o.id)} className={`rounded-2xl border p-4 text-left font-medium ${selected === o.id ? (o.id === current.correctOptionId ? "border-green-500 bg-green-50" : "border-red-500 bg-red-50") : "hover:bg-slate-50"}`}>{o.label}</button>)}</div>{selected && <p className="mt-4 rounded-2xl bg-slate-50 p-4">{selected === current.correctOptionId ? "Correct! " : "Not quite. "}{current.explanation}</p>}<button disabled={!selected} onClick={next} className="mt-6 w-full rounded-2xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40">{index === session.length - 1 ? "Finish" : "Next"}</button></div></main>;
}
