import { Story } from "@/types/content";

export const grade2GardenClock: Story = {
  id: "benchmark-grade-2-the-garden-clock",
  title: "The Garden Clock",
  description: "Zuri and her friends bring a tired school garden back to life while learning to notice, plan and care for living things.",
  subject: "english",
  grade: 2,
  gradeBand: "lower_primary",
  levelLabel: "Grade 2 Adventure",
  icon: "🌻",
  gradient: "from-yellow-400 to-emerald-600",
  estimatedMinutes: 14,
  xp: 100,
  unlocksAtLevel: 1,
  status: "ready",
  scenes: [
    { id: "s1", text: "Behind Zuri's school there is a small garden. It has green plants, yellow flowers and a narrow path. But today the soil is dry, and some leaves lie on the ground. Zuri stops at the gate and looks carefully.", illustration: "👧🏾🌻🏫" },
    { id: "s2", text: "On the garden wall, Zuri sees an old clock. Its hands have stopped. The garden clock does not tell the right time. Zuri wonders when it stopped and why nobody has cared for the garden.", illustration: "⏰🌿🔎" },
    { id: "s3", text: "The next day, Zuri brings her friends Akinyi and Timo. She tells them about the dry garden. They look at the plants together. Akinyi notices dry leaves. Timo finds an empty water can.", illustration: "👧🏾🧒🏾🪣" },
    { id: "s4", text: "The children make a simple plan. Akinyi collects dry leaves. Timo fills the water can. Zuri checks the plants. They agree to work in the garden each afternoon.", illustration: "📝🌿💧" },
    { id: "s5", text: "On the first afternoon, the children water the plants. They pull out small weeds and clear the path. The work is hard, but they keep going. When they finish, the garden looks cleaner.", illustration: "💧🌱🧹" },
    { id: "s6", text: "The next afternoon, Zuri notices that one plant still looks weak. Its leaves are pale. She does not pull it out. Instead, she checks the soil and moves the plant to a place with more sunlight.", illustration: "🌱☀️👧🏾" },
    { id: "s7", text: "For three days, Zuri watches the plant. The children water it carefully. On the third day, a new green leaf appears. Zuri smiles. She tells her friends, 'We looked closely, so we found out what the plant needed.'", illustration: "🌱😊👧🏾" },
    { id: "s8", text: "The friends start a garden notebook. Each day they draw a plant and write a short sentence about it. On Monday they write, 'The plant looks weak.' On Thursday they write, 'The plant has a new leaf.'", illustration: "📓🌱✏️" },
    { id: "s9", text: "Their teacher visits on Friday. She walks along the clean path and looks at the healthy plants. She reads the garden notebook. 'You watched the plants and worked as a team,' she says. The children feel proud.", illustration: "👩🏾‍🏫🌿👏🏾" },
    { id: "s10", text: "The teacher asks the children to explain what changed. Zuri says the garden was dry, but the plants became stronger after the children cared for them. Timo adds that the notebook helped them remember what they saw.", illustration: "🗣️📓🌻" },
    { id: "s11", text: "The old clock is still on the wall. The children ask the school caretaker to help them fix it. Soon the hands move again. The garden clock now shows the correct time when the children begin their afternoon work.", illustration: "⏰🔧🌿" },
    { id: "s12", text: "A few weeks later, other pupils visit the garden. They see bright flowers and fresh green leaves. Zuri gives them the garden notebook. 'Look carefully, make a plan and keep trying,' she says. The children know that small actions can make a big difference.", illustration: "🌻🧒🏾📓✨" },
  ],
  questions: [
    { id: "q1", prompt: "What was wrong with the garden at the beginning?", options: [{ id: "a", text: "The soil was dry and some plants were weak." }, { id: "b", text: "It was full of toys." }, { id: "c", text: "It was covered in snow." }, { id: "d", text: "There were no plants." }], correctOptionId: "a", explanation: "The garden was dry and some plants were weak.", skills: ["reading_comprehension", "vocabulary"], xp: 15 },
    { id: "q2", prompt: "What did the children do first to help the garden?", options: [{ id: "a", text: "They made a simple plan." }, { id: "b", text: "They fixed the clock." }, { id: "c", text: "They picked all the flowers." }, { id: "d", text: "They closed the gate." }], correctOptionId: "a", explanation: "They looked at the garden and made a simple plan before they started work.", skills: ["reading_comprehension", "reading_comprehension"], xp: 15 },
    { id: "q3", prompt: "Why did Zuri move the weak plant?", options: [{ id: "a", text: "She thought it needed more sunlight." }, { id: "b", text: "She wanted to throw it away." }, { id: "c", text: "She wanted to hide it." }, { id: "d", text: "The clock told her to move it." }], correctOptionId: "a", explanation: "Zuri checked the plant and moved it to a place with more sunlight.", skills: ["reading_comprehension", "vocabulary"], xp: 15 },
    { id: "q4", prompt: "Which sentence tells what happened before now?", options: [{ id: "a", text: "Zuri watches the plant." }, { id: "b", text: "Zuri watched the plant." }, { id: "c", text: "Zuri will watch the plant." }, { id: "d", text: "Zuri is the plant." }], correctOptionId: "b", explanation: "Watched tells us the action happened before now.", skills: ["grammar"], xp: 15 },
    { id: "q5", prompt: "Which word helps show the order of events?", options: [{ id: "a", text: "Next" }, { id: "b", text: "Yellow" }, { id: "c", text: "Garden" }, { id: "d", text: "Weak" }], correctOptionId: "a", explanation: "Next helps the reader know what happened after the previous event.", skills: ["grammar", "reading_comprehension"], xp: 15 },
    { id: "q6", prompt: "Put the ideas in the right order: The children made a plan. They watered the plants. The garden became healthier.", options: [{ id: "a", text: "Plan → water → garden becomes healthier" }, { id: "b", text: "Water → healthier → plan" }, { id: "c", text: "Healthier → plan → water" }, { id: "d", text: "Plan → healthier → water" }], correctOptionId: "a", explanation: "The children planned first, then cared for the plants, and the garden improved.", skills: ["grammar", "reading_comprehension"], xp: 15 },
    { id: "q7", prompt: "Which sentence is best for the garden notebook?", options: [{ id: "a", text: "The plant has a new green leaf." }, { id: "b", text: "New plant leaf green has." }, { id: "c", text: "Has green plant the leaf." }, { id: "d", text: "Leaf plant new." }], correctOptionId: "a", explanation: "The words are in a clear sentence pattern and tell the reader what happened.", skills: ["grammar", "writing"], xp: 15 },
    { id: "q8", prompt: "What lesson did the children learn?", options: [{ id: "a", text: "Careful work and teamwork can improve a place." }, { id: "b", text: "Plants do not need water." }, { id: "c", text: "A clock can grow flowers." }, { id: "d", text: "Working alone is always best." }], correctOptionId: "a", explanation: "The children worked together, watched carefully and cared for the garden.", skills: ["reading_comprehension", "vocabulary"], xp: 20 },
  ],
};
